# -*- coding: utf-8 -*-
"""Map for https://www.saucedemo.com/ (Swag Labs) — generated by /explore-site.

Sauce Labs' public test-automation demo, so interacting (including logging in
with the published demo credentials) is safe and intended. Covers the login flow
and the shopping surfaces reached from it.

Probed facts baked in:
- login fields have no DOM `required`, but the app enforces them (empty submit →
  inline "Epic sadface" error), so they're marked required to fuzz;
- the burger menu's items (Logout, Reset App State) are hidden until "Open Menu"
  is clicked → modeled as a toggle;
- product tiles open an item-detail page; the cart icon opens the cart.
"""
from edumaze import (DESKTOP, MOBILE, Budgets, Click, Element, Field, Site,
                     State, Submit, Toggle, css, placeholder, role, text)


class Login(State):
    url = "/"

    def elements(self):
        return [
            Element(css('[data-test="error"]'), visible=False, info=True),  # no error yet
            Element(role("button", "Login"), name="Login",
                    submit=Submit(
                        fields=[Field(placeholder("Username"), required=True),
                                Field(placeholder("Password"), required=True)],
                        on_valid=Inventory,
                        invalid_shows=css('[data-test="error"]'))),
        ]


class Inventory(State):
    url = "/inventory.html"

    def elements(self):
        return [
            Element(role("button", "Open Menu"), name="Open Menu",
                    toggle=Toggle(reveals=[text("Logout"), text("Reset App State")])),
            Element(text("Logout"), visible=False, info=True),          # hidden until menu
            Element(text("Reset App State"), visible=False, info=True),
            Element(role("button", "Add to cart"), name="Add to cart", click=Click()),
            Element(role("link", "Sauce Labs Backpack"), name="Product",
                    click=Click(to=ItemDetail)),
            Element(css(".shopping_cart_link"), name="Cart", click=Click(to=Cart)),
        ]


class ItemDetail(State):
    url = "/inventory-item.html"

    def elements(self):
        return [
            Element(role("button", "Back to products"), name="Back",
                    click=Click(to=Inventory)),
            Element(role("button", "Add to cart"), name="Add to cart", click=Click()),
        ]


class Cart(State):
    url = "/cart.html"

    def elements(self):
        return [
            Element(role("button", "Continue Shopping"), name="Continue Shopping",
                    click=Click(to=Inventory)),
            Element(role("button", "Checkout"), name="Checkout", click=Click()),
        ]


class SauceDemo(Site):
    id = "saucedemo"
    base_url = "https://www.saucedemo.com/"
    domain_allowlist = ["www.saucedemo.com"]
    entry = Login
    viewports = [DESKTOP, MOBILE]
    budgets = Budgets(max_actions=60)
    seed_data = {"Username": "standard_user", "Password": "secret_sauce"}
