# -*- coding: utf-8 -*-
"""Map for https://the-internet.herokuapp.com/ — generated by /check-site.

Sauce Labs' public UI playground (safe to interact). Covers the form-auth flow:
Home → Login → Secure, with logout back to Login.

Probed facts baked in:
- login inputs have no placeholder/label-name usable as an accessible name, so
  they're targeted by CSS id (#username / #password);
- valid creds (tomsmith / SuperSecretPassword!) → /secure; empty/invalid → stays
  on /login and shows the #flash error;
- the #flash banner must NOT be present on a fresh login page.
"""
from edumaze import (DESKTOP, MOBILE, Budgets, Click, Element, Field, Site,
                     State, Submit, css, role)


class Home(State):
    url = "/"

    def elements(self):
        return [
            Element(role("heading", "Welcome to the-internet"), info=True),
            Element(role("link", "Form Authentication"), name="Form Authentication",
                    click=Click(to=Login)),
        ]


class Login(State):
    url = "/login"

    def elements(self):
        return [
            Element(role("heading", "Login Page"), info=True),
            Element(css("#flash"), visible=False, info=True),   # no flash on a fresh page
            Element(role("button", "Login"), name="Login",
                    submit=Submit(
                        fields=[Field(css("#username"), required=True, valid="tomsmith"),
                                Field(css("#password"), required=True,
                                      valid="SuperSecretPassword!")],
                        on_valid=Secure,
                        invalid_shows=css("#flash"))),
        ]


class Secure(State):
    url = "/secure"

    def elements(self):
        return [
            Element(role("heading", "Secure Area"), info=True),
            Element(role("link", "Logout"), name="Logout", click=Click(to=Login)),
        ]


class TheInternet(Site):
    id = "theinternet"
    base_url = "https://the-internet.herokuapp.com/"
    domain_allowlist = ["the-internet.herokuapp.com"]
    entry = Home
    viewports = [DESKTOP, MOBILE]
    budgets = Budgets(max_actions=40)
